spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer-db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
